# Arbo de decisión

Modelo de predicción utilizado por una gran cantidad de áreas.

Dado un conjunto de datos se fabrican diagramas de construcciones lógicas, que sirven para representar y categorizar una serie de condiciones que ocurren de forma sucesica, para la resolución de un problema.

## Ejemplo - clasificación

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
import seaborn as sns

In [2]:
cd data_sets

e:\Sergio\Documentos\Programacion\Python\Udemy Machine Free\data_sets


In [3]:
ls

 El volumen de la unidad E es Principal
 El n�mero de serie del volumen es: 580F-2192

 Directorio de e:\Sergio\Documentos\Programacion\Python\Udemy Machine Free\data_sets

11/03/2021  07:09 p. m.    <DIR>          .
11/03/2021  07:09 p. m.    <DIR>          ..
08/12/2020  03:56 p. m.           371,432 archive.zip
11/12/2019  02:17 a. m.             3,258 gender_submission.csv
11/12/2019  02:17 a. m.            28,629 test.csv
08/12/2020  04:45 p. m.            34,877 titanic.zip
11/12/2019  02:17 a. m.            61,194 train.csv
25/09/2019  08:26 a. m.           726,209 USA_Housing.csv
21/01/2021  02:12 p. m.            86,768 vehiculos.csv
11/03/2021  07:09 p. m.            12,895 vino.csv
               8 archivos      1,325,262 bytes
               2 dirs  719,951,699,968 bytes libres


In [4]:
vinos = pd.read_csv('vino.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [5]:
vinos['Wine Type'].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [7]:
vinos['Wine Type'].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [11]:
X = vinos.drop('Wine Type',axis=1)

In [12]:
X

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [13]:
y = vinos['Wine Type']

In [14]:
y

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [15]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
arbol = DecisionTreeClassifier()

In [26]:
arbol.fit(X_train,y_train)

DecisionTreeClassifier()

In [28]:
predicciones = arbol.predict(X_test)

In [29]:
predicciones

array(['Three', 'Three', 'Three', 'Three', 'One', 'Two', 'One', 'Two',
       'Three', 'One', 'Three', 'Three', 'Two', 'Two', 'One', 'One',
       'Three', 'Two', 'Two', 'Two', 'Two', 'One', 'Three', 'Three',
       'Two', 'Two', 'One', 'One', 'Two', 'Three', 'Three', 'Two',
       'Three', 'Two', 'Two', 'Two', 'Two', 'Three', 'One', 'Three',
       'One', 'Two', 'One', 'One', 'Three', 'One', 'Two', 'One', 'One',
       'Two', 'Three', 'Two', 'One', 'One'], dtype=object)

In [30]:
y_test

167    Three
137    Three
156    Three
59       Two
26       One
118      Two
11       One
82       Two
136    Three
34       One
163    Three
152    Three
90       Two
27       One
50       One
9        One
159    Three
72       Two
109      Two
77       Two
81       Two
33       One
171    Three
147    Three
4        One
100      Two
18       One
48       One
161    Three
154    Three
133    Three
88       Two
145    Three
124      Two
85       Two
89       Two
105      Two
170    Three
37       One
142    Three
46       One
113      Two
143    Three
29       One
175    Three
10       One
119      Two
52       One
49       One
94       Two
157    Three
125      Two
35       One
8        One
Name: Wine Type, dtype: object

In [32]:
from sklearn.metrics import classification_report, confusion_matrix

In [33]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.94      0.89      0.91        18
       Three       0.94      0.89      0.91        18
         Two       0.85      0.94      0.89        18

    accuracy                           0.91        54
   macro avg       0.91      0.91      0.91        54
weighted avg       0.91      0.91      0.91        54



In [36]:
print(confusion_matrix(y_test,predicciones))

[[16  0  2]
 [ 1 16  1]
 [ 0  1 17]]
