# Numpy arrays

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4]

In [3]:
array = np.array(lista)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

In [9]:
array_arange = np.arange(5)

In [10]:
array

array([1, 2, 3, 4])

In [11]:
inicio_fin = np.arange(2,10)

In [12]:
inicio_fin

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
pasos = np.arange(3,31,2)

In [14]:
pasos

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

### zeros

In [15]:
zeros = np.zeros(3)

In [16]:
zeros

array([0., 0., 0.])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones

In [18]:
one = np.ones(9)

In [19]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [21]:
linspace = np.linspace(1,10,7)

In [22]:
linspace

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### eye

In [23]:
eye = np.eye(5)

In [24]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Numeros aleatorios

### rand

In [25]:
np.random.rand(5)

array([0.12891806, 0.27192123, 0.51997751, 0.92023869, 0.82802286])

In [26]:
np.random.rand(2,3)

array([[0.78651305, 0.78436878, 0.11627567],
       [0.6968962 , 0.79934145, 0.02676208]])

### randn

In [27]:
np.random.randn(7)

array([-1.31432192,  0.5586629 , -1.58774774,  0.91030107,  1.15589222,
       -0.39261692, -0.9962819 ])

In [28]:
np.random.randn(2,4)

array([[ 0.01334695,  0.72995209,  0.45217921, -2.27155126],
       [-1.03275142, -0.21807077, -0.59650796,  0.87651899]])

### randint

In [29]:
np.random.randint(2,5)

2

In [30]:
np.random.randint(2,900)

365

In [31]:
np.random.randint(2,300,22)

array([118,  52, 266, 198,  59,  81, 199, 212, 126,  11, 188, 197, 194,
        79,  60,  91, 248, 187, 211, 129, 273, 253])

## Cambiar tamaños

### reshape

In [32]:
array = np.random.randint(1,100,21)

In [33]:
array

array([ 4, 10, 77,  6, 52,  5, 71, 80, 71, 88, 43, 71, 35, 22, 43, 44,  8,
       90, 81, 16, 73])

In [34]:
matriz = array.reshape(7,3)

In [35]:
matriz

array([[ 4, 10, 77],
       [ 6, 52,  5],
       [71, 80, 71],
       [88, 43, 71],
       [35, 22, 43],
       [44,  8, 90],
       [81, 16, 73]])

## Maximos y minimos

In [36]:
array = np.random.randint(1,100,50)

In [37]:
array

array([43, 27, 71, 57, 46, 16, 46,  9, 42, 11, 15, 90, 79, 26, 41, 31, 48,
        9, 36, 43, 36, 98, 46, 43, 83, 40, 94, 52, 81, 97, 40, 51, 18, 29,
       38, 35, 80, 54, 65, 91, 30, 72,  3,  3, 17, 89, 30, 84, 29,  6])

### max

In [38]:
maximo = array.max()

In [39]:
maximo

98

In [40]:
posicion_max = array.argmax()

In [41]:
#da el lugar que ocupa el valor maximo

In [42]:
posicion_max

21

### min

In [43]:
minimo = array.min()

In [44]:
minimo

3

In [45]:
posicion_min = array.argmin()

In [46]:
#da el lugar que ocupa el valor minimo

In [47]:
posicion_min

42

## Indexaciones

### 1 dimension

In [48]:
array = np.arange(0,10)

In [49]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
array[3]

3

In [51]:
array[-8]

2

In [52]:
array[3:-1]

array([3, 4, 5, 6, 7, 8])

In [53]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array[:4]

array([0, 1, 2, 3])

In [55]:
array2 = array.copy()

In [56]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
array2[0] = 100

In [58]:
array2[0]

100

### dos dimensiones

In [59]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [60]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
array[0]

array([1, 2, 3])

In [62]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
array2 = array[:2]

In [64]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
array[0][0]

1

In [67]:
array[0,0]

1

In [68]:
array[1,1]

5

In [69]:
array[:,0]

array([1, 4, 7])

In [70]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Selección de elementos

In [71]:
array = np.arange(2,14)

In [72]:
array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [73]:
condicion = array > 5

In [74]:
condicion

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True])

In [75]:
array[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [76]:
array[array > 8]

array([ 9, 10, 11, 12, 13])

In [77]:
array[array % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

### Operaciones

In [78]:
array = np.arange(0,10)

In [79]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
array * array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [81]:
array2 = np.arange(5,15)

In [82]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [83]:
array * array2

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [84]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [85]:
np.max(array)

9