# Random forest

Es una combinación de árboles de desición, donde cada árbol selecciona una clase y luego se combinan las decisiones de cada árbol, para seleccionar una clase final ganadora.

Es muy eficiente con una presición alta. Útil para bd grandes.

## Ejercicio

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
cd data_sets

e:\Sergio\Documentos\Programacion\Python\Udemy Machine Free\data_sets


In [7]:
vinos = pd.read_csv('vino.csv')
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [9]:
X = vinos.drop('Wine Type', axis=1)
y = vinos['Wine Type']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
randomforest = RandomForestClassifier(n_estimators=80)

In [14]:
randomforest.fit(X_train, y_train)

RandomForestClassifier(n_estimators=80)

In [15]:
predicciones = randomforest.predict(X_test)

In [16]:
print(predicciones)

['Three' 'Three' 'Two' 'Two' 'One' 'One' 'One' 'One' 'Two' 'Three' 'One'
 'Three' 'Two' 'One' 'Two' 'Two' 'One' 'Three' 'Three' 'One' 'Two' 'Three'
 'Two' 'One' 'One' 'Two' 'Two' 'Two' 'Two' 'Two' 'Two' 'One' 'Three' 'One'
 'Two' 'Three' 'Two' 'Three' 'Two' 'Three' 'Three' 'Three' 'Two' 'One'
 'Three' 'One' 'One' 'One' 'One' 'Three' 'Three' 'Two' 'One' 'One']


In [17]:
y_test

145    Three
154    Three
116      Two
66       Two
1        One
55       One
4        One
40       One
112      Two
131    Three
54       One
151    Three
88       Two
18       One
61       Two
72       Two
45       One
140    Three
175    Three
22       One
94       Two
147    Three
69       Two
2        One
24       One
59       Two
99       Two
105      Two
115      Two
106      Two
93       Two
16       One
146    Three
53       One
126      Two
150    Three
125      Two
167    Three
121      Two
173    Three
164    Three
130    Three
82       Two
9        One
137    Three
13       One
14       One
73       Two
6        One
152    Three
153    Three
75       Two
39       One
15       One
Name: Wine Type, dtype: object

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test,predicciones))

              precision    recall  f1-score   support

         One       0.95      1.00      0.97        18
       Three       1.00      1.00      1.00        16
         Two       1.00      0.95      0.97        20

    accuracy                           0.98        54
   macro avg       0.98      0.98      0.98        54
weighted avg       0.98      0.98      0.98        54



In [22]:
print(confusion_matrix(y_test,predicciones))

[[18  0  0]
 [ 0 16  0]
 [ 1  0 19]]
